pipeline {
    agent any

    stages {

        stage('Build Image') {
            steps {
                dir('website') {
                    sh 'docker build -t website:v1 .'
                }
            }
        }

        stage('Tag Image') {
            steps {
                sh 'docker tag website:v1 884576820568.dkr.ecr.us-west-2.amazonaws.com/website:v1'
            }
        }

        stage('Push ECR') {
    steps {
        sh '''
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 884576820568.dkr.ecr.us-west-2.amazonaws.com

        docker push 884576820568.dkr.ecr.us-west-2.amazonaws.com/website:v1
        '''
    }
}
    }
}