pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'YOUR_GITHUB_REPO'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t website:v1 .'
            }
        }

        stage('Run Test') {
            steps {
                sh 'docker images'
            }
        }
    }
}